### PR TITLE
Support molecule testing. lint.

### PR DESCRIPTION
**Pull request by dhutty**
Add support for testing with [molecule](http://molecule.readthedocs.io)

### CODE REVIEW

**Comment by t2d** [comment]
Thank you for your PR! We will try out molecule and get back to you.

**Comment by t2d** [comment]
I like the idea of molecule and it works nicely with travis ci. But there are some downsites. With this PR, we'll be using docker, travis ci, tox and vagrant for testing. The amount of test files almost trumps the amount of actual ansible files.

- .travis.yml
- molecule.yml
- playbook.yml
- requirements.txt
- tests/inventory
- tests/test_default.py
- tests/test.yml
- tox.ini
- Vagrantfile
- vagrant.yml

I believe this doesn't make it easier to actually contribute. I think, if we accept this PR, we should at least drop vagrant since it is replaced by docker. What do others think?

The second turn off is the fact that docker takes a long time to build the docker container. Can't we use a standard container @dhutty ?

**Comment by 0x46616c6b** [comment]
Maybe we can move all test related files except the .travis.yml to the tests/ directory, so its clearer.

**Comment by dhutty** [comment]
On 4/14/17 5:38 AM, t2d wrote:
> I like the idea of molecule and it works nicely with travis ci. But there are some downsites. With this PR, we'll be using docker, travis ci, tox and vagrant for testing. The amount of test files almost trumps the amount of actual ansible files.
>
> - .travis.yml
> - molecule.yml
> - playbook.yml
> - requirements.txt
> - tests/inventory
> - tests/test_default.py
> - tests/test.yml
> - tox.ini
> - Vagrantfile
> - vagrant.yml
>
> I believe this doesn't make it easier to actually contribute. I think, if we accept this PR, we should at least drop vagrant since it is replaced by docker. What do others think?

1) I quite agree that this proliferation of testing-fu does increase the 
level of understanding required and is therefore raising the bar for 
contributors. (Although I think perhaps it's not just better but easier 
once a contributor does have sufficient familiarity with the toolset). I 
recognise that I am an outsider and don't know your normal contributor 
base or your use case. I will not feel in the slightest bit offended if 
you don't want to include this.

2) I'll happily excise the Vagrant support if you want
>
> The second turn off is the fact that docker takes a long time to build the docker container. Can't we use a standard container @dhutty ?

3) Quite likely we can; I picked these images based a simple search on 
docker hub. The only reason I specified systemd was so that there would 
some (any!) service manager in the container because otherwise the 
Ansible 'service' task would no doubt fail. Perhaps the container images 
'debian' and 'ubuntu' would work and be more suitable?

-- 
Duncan Hutty
http://www.allgoodbits.org

**Comment by t2d** [comment]
I cleaned up a lot of files and relocated others. Now we only have `molecule.yml` and `tox.ini` in the main folder. I can live with this as those are actually distinctive tools. I like that the testing is now identical locally and on Travis CI. 
```
Travis CI -> Tox (multiplexes ansible) -> Molecule (multiplexes OS)

Molecule creates x Docker instances. Then calls ansible to run on all those machines.
```
Thanks again for the PR.

**Pull request merged**
